name = "nas-query"
main = "src/index.js"
compatibility_date = "2025-06-01"

[vars]
# 前缀保留：同域名 API 收敛时使用
ROUTES = "/nas/realtime,/nas/history,/health"

[[d1_databases]]
binding = "DB"
database_name = "nas-history"
database_id = "1f47dbb7-388e-4544-ad01-84e62a904dfe"

[[kv_namespaces]]
binding = "KV"
id = "902cef368819436a96c20163cb9eacd6"